{
 "title": "The Innovation Game Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tig_price",
    "query": {
     "query": "query_result(tig_block_info{metric=\"priceUsd\"})"
    }
   },
   { "name": "donate_address", "query": "${VAR_DONATE_ADDRESS}" },
   { "name": "player_ids", "label": "Addresses", "query": { "query": "label_values(player_id)" } },
   { "name": "round", "label": "Round", "query": { "query": "label_values(round)" } },
   { "name": "stat_range_time", "label": "Statistics range time", "query": "1h : 1,6h : 6,24h : 24" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$tig_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wallet balance (TIG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"deposit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"priceUsd\"}[7d]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$round", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "# Support our work with TIG donation\n[$donate_address](https://basescan.org/address/$donate_address)"
   },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"rewards\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wallet balance ($)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Total donations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groq": "*",
     "parser": "uql",
     "root_selector": "items.to\n",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"items\"\n| where \"to.hash\" == '$donate_address'\n| project sum(\"total.value\")",
     "url": "https://base.blockscout.com/api/v2/addresses/$donate_address/token-transfers?token=0x0C03Ce270B4826Ec62e7DD007f0B716068639F7B",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Volume 24H",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"priceVolume\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liquidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"priceLiquidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Change 24H",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"priceChange\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time left",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"round_blocks_left\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_block_info{metric=\"height\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Innovator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "show_innovator" },
  {
   "title": "Innovator Round Balance (TIG)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_innovator_data{metric=\"round_earnings\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated TIG (round) (innovator)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$D+($A*$B)", "type": "math" }
   ]
  },
  {
   "title": "Innovator balance (TIG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(tig_innovator_data{metric=\"round_earnings\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Innovator rewards (TIG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "sum(tig_innovator_data{metric=\"reward\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Innovator Round balance ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Estimated $ (round)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  { "title": "Benchmarker stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Round balance (TIG)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"round_earnings\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated TIG (end round)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$D+($A*$B)", "type": "math" }
   ]
  },
  {
   "title": "Estimated TIG / day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tig_player_data{metric=\"round_earnings\",round=~\"$round|\"}[${stat_range_time:text}]))*(24/${stat_range_time:value})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated TIG / month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tig_player_data{metric=\"round_earnings\",round=~\"$round|\"}[${stat_range_time:text}]))*(24/${stat_range_time:value})*30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"reward\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round balance (TIG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"round_earnings\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tig_player_data{metric=\"reward\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TIG/hour",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"round_earnings\",round=~\"$round|\"})/(tig_block_info{metric=\"blocks_per_round\"} - ignoring(metric)tig_block_info{metric=\"round_blocks_left\"})*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round balance ($)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Estimated $ (end round)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Estimated $ / day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 71 }
   ]
  },
  {
   "title": "Estimated $ / month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 72 }
   ]
  },
  {
   "title": "Cutoff",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"cutoff\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Penalty",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"imbalance_penalty\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "last_over_time(tig_player_data{round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solutions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 28 },
   "targets": [
    {
     "expr": "sum(tig_challenge_data{metric=\"num_qualifiers_by_challenge\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solutions (by algo)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 28 },
   "targets": [
    {
     "expr": "sum by(algorithm_name) (tig_algorithm_data{metric=\"num_qualifiers_by_algo\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$player_ids", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "player_ids" },
  {
   "title": "Round balance (TIG) (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_player_data{metric=\"round_earnings\",player_id=\"${player_ids}\",round=~\"$round|\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated TIG (end round) (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$D+($A*$B)", "type": "math" }
   ]
  },
  {
   "title": "Estimated TIG / day (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tig_player_data{metric=\"round_earnings\",round=~\"$round|\",player_id=\"${player_ids}\"}[${stat_range_time:text}]))*(24/${stat_range_time:value})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated TIG / month (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tig_player_data{metric=\"round_earnings\",round=~\"$round|\",player_id=\"${player_ids}\"}[${stat_range_time:text}]))*(24/${stat_range_time:value})*30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_player_data{metric=\"reward\",player_id=\"${player_ids}\",round=~\"$round|\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round balance (TIG) (${player_ids}\")",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 39 },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"round_earnings\",player_id=\"${player_ids}\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tig_player_data{metric=\"reward\",player_id=\"${player_ids}\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TIG/hour",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tig_player_data{metric=\"round_earnings\",player_id=\"${player_ids}\",round=~\"$round|\"})/(tig_block_info{metric=\"blocks_per_round\"} - ignoring(metric)tig_block_info{metric=\"round_blocks_left\"})*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round balance ($) (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 27 }
   ]
  },
  {
   "title": "Estimated $ (end round) (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Estimated $ / day (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 74 }
   ]
  },
  {
   "title": "Estimated $ / month (${player_ids}\")",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 75 }
   ]
  },
  {
   "title": "Cutoff",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_player_data{metric=\"cutoff\",player_id=\"${player_ids}\",round=~\"$round|\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Penalty",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tig_player_data{metric=\"imbalance_penalty\",player_id=\"${player_ids}\",round=~\"$round|\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Challenge",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "last_over_time(tig_challenge_data{player_id=\"${player_ids}\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solutions (${player_ids}\")",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "sum(tig_challenge_data{metric=\"num_qualifiers_by_challenge\",player_id=\"${player_ids}\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solutions (by algo) (${player_ids}\")",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 47 },
   "targets": [
    {
     "expr": "sum by(algorithm_name) (tig_algorithm_data{metric=\"num_qualifiers_by_algo\",player_id=\"${player_ids}\",round=~\"$round|\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}